-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

-- | The abstract syntax of language arith.
module Arith.Abs where

import qualified Prelude as C (Eq, Ord, Read, Show)

data Exp
  = ETrue
  | EFalse
  | ECond Exp Exp Exp
  | EZero
  | ESucc Exp
  | EPred Exp
  | EIsZero Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)
